## These 2 functions working together will take a square matrix and return the
## inverse using the built in solve() function. The input to makeCacheMatrix
## must be a square matrix.

## makeCacheMatrix will return a list of 4 functions. 3 of them are needed to
## be passed on to cacheSolve. The list item 'set' can be used to redefine
## the matrix. By default an empty matrix is created.

makeCacheMatrix <- function(x = matrix()) {
    inv <- NULL
    set <- function(y){
        x <<- y
        inv <<- NULL
    }
    get <- function() x
    setinv <- function(inverse) inv <<- inverse
    getinv <- function() inv
    list(set = set,
         get = get,
         setinv = setinv,
         getinv = getinv)
}


## cacheSolve will take the list of functions generated by makeCacheMatrix
## and check to see if the inverse of the inputed matrix is cached. If so,
## the cached matrix is returned. If not, the inverse will be computed, cached
## for future use, and then returned.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
    inv <- x$getinv()
    if(!is.null(inv)){
        message("getting cached data")
        return(inv)
    }
    data <- x$get()
    inv <- solve(data, ...)
    x$setinv(inv)
    inv
}
